### ISSUE TITLE
Unchecked runtime.lastError on closed tab

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1245]
Unchecked runtime.lastError while running browserAction.setTitle: No tab with id: 153.
    at Object.setIcon (chrome-extension://bgfakkfcmbdaaeifhgdfeodkafhklfef/js/vapi-background.js:777:27)
    at Object.updateBadge (chrome-extension://bgfakkfcmbdaaeifhgdfeodkafhklfef/js/tab.js:918:14)

**Comment by mneunomne** [comment]
Don't remember ever catching this bug. Probably outdated by now.
