### ISSUE TITLE
google textparser error on mobile

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2224]
In google it seems that the html structure for ads is different. Need a workaround for when it is mobile:

```
textads.js:174 Uncaught TypeError: Cannot read properties of undefined (reading 'childNodes')
    at Object.googleText [as handler] (textads.js:174:61)
    at checkFilters (textads.js:463:28)
    at Object.process (textads.js:476:21)
    at Object.process (parser.js:377:29)
    at vAPI.adCheck (parser.js:34:27)
    at processFilters (contentscript.js:1343:30)
    at vAPI.SafeAnimationFrame.bootstrapPhaseAdn [as callback] (contentscript.js:1325:13)
    at vAPI.SafeAnimationFrame.onRAF (contentscript.js:238:14)
    at contentscript.js:207:64
```

This can also be reproduced in mobile device simular with the developer tools.

**Comment by mneunomne** [comment]
https://github.com/dhowe/AdNauseam/pull/2225 partially fixes it (only avoids exception so the parser doesn't break). Need to somehow check if it is mobile and have different parser structure.
