### ISSUE TITLE
Type Error appears when tab is closed during processing ads

### ISSUE THREAD

**Issue by SkeLLLa** [dhowe/AdNauseam#970]
If I close tab during the process of clicking ads on it, sometimes it will result in uncaught type error.
```
Error in response to tabs.get: TypeError: Cannot read property 'id' of undefined
    at startInTab (chrome-extension://meiocdbhagboionnkkcbmajecfahdblc/js/vapi-background.js:1283:40)
    at Object.callback (chrome-extension://meiocdbhagboionnkkcbmajecfahdblc/js/vapi-background.js:1312:48)
    at Object.vAPI.onLoadAllCompleted (chrome-extension://meiocdbhagboionnkkcbmajecfahdblc/js/vapi-background.js:1312:21)
    at Object.µBlock.adnauseam.exports.injectContentScripts (chrome-extension://meiocdbhagboionnkkcbmajecfahdblc/js/adn/core.js:1574:25)
    at chrome-extension://meiocdbhagboionnkkcbmajecfahdblc/js/adn/core.js:2009:42
    at chrome-extension://meiocdbhagboionnkkcbmajecfahdblc/js/vapi-background.js:805:17
```

It appears in 
```js
    var startInTab = function(tab, frameId) { // ADN
        var µb = µBlock;
        µb.tabContextManager.commit(tab.id, tab.url); // error here
        µb.bindTabToPageStats(tab.id);
        // https://github.com/chrisaljoudi/uBlock/issues/129
        if ( /^https?:\/\//.test(tab.url) ) { // added in ub/1.10.0
          scriptStart(tab.id, frameId);
        }
    };
```

Probably callback fires when tab with provided id is already closed:

```js
chrome.tabs.get(tabId, function(tab) { startInTab(tab, frameId); }); // ADN
```

So it's better to add somewhere check on `tab` if it's defined or not.

AdNausem v3.3.32. OS - doesn't matter, appears on windows, linux.

**Comment by dhowe** [comment]
thanks @SkeLLLa

**Comment by cqx931** [comment]
Fixed https://github.com/dhowe/AdNauseam/pull/975, please check
